# Generated by Django 3.1.5 on 2021-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('academic_degree', models.CharField(blank=True, db_index=True, max_length=300)),
                ('position', models.CharField(blank=True, db_index=True, max_length=200)),
                ('education', models.TextField(blank=True, db_index=True)),
                ('work_experience', models.TextField(blank=True, db_index=True)),
                ('international_experience', models.TextField(blank=True, db_index=True)),
                ('сompetitive_advantages', models.CharField(blank=True, db_index=True, max_length=300)),
                ('training', models.TextField(blank=True, db_index=True)),
                ('academic_activity', models.TextField(blank=True, db_index=True)),
                ('training_courses', models.CharField(blank=True, db_index=True, max_length=300)),
                ('scientific_publications', models.TextField(blank=True, db_index=True)),
                ('thumbnail', models.ImageField(default='member_default.jpg', upload_to='staff_images')),
                ('tags', models.ManyToManyField(blank=True, related_name='members', to='staff.Tag')),
            ],
        ),
    ]
