# Generated by Django 3.1.5 on 2021-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('edu_code', models.CharField(max_length=7, unique=True)),
                ('body', models.TextField(db_index=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('academic_key', models.CharField(max_length=2)),
                ('study_period', models.PositiveSmallIntegerField(blank=True, default=4)),
                ('study_price', models.PositiveIntegerField(blank=True)),
                ('purpose', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
